### ISSUE TITLE
expected file (...)/base_helper_decorator.rb to define constant Spree::BaseHelperDecorator, but didn't

### ISSUE THREAD

**Issue by b1nary** [karmakatahdin/solidus_seo#8]
I am new to Solidus so i am not sure if there is a issue on my side, however i just started building a shop and all other plugins that show they are supported on the current version worked flawlessly so far. 

Basically i get the following error as soon as i try to start the server or run the required bundle command when after i add your Gem to my Gemfile. I also tried the master, but no luck either. 

I assume i miss support for that decorator pattern somehow? 

```Exiting
Traceback (most recent call last):
	90: from bin/rails:3:in `<main>'
	89: from bin/rails:3:in `load'
	88: from /home/roman/code/Kawaii/bin/spring:15:in `<top (required)>'
	87: from /home/roman/code/Kawaii/bin/spring:15:in `require'
	86: from /home/roman/.rvm/gems/ruby-2.5.1/gems/spring-2.1.0/lib/spring/binstub.rb:11:in `<top (required)>'
	85: from /home/roman/.rvm/gems/ruby-2.5.1/gems/spring-2.1.0/lib/spring/binstub.rb:11:in `load'
	84: from /home/roman/.rvm/gems/ruby-2.5.1/gems/spring-2.1.0/bin/spring:49:in `<top (required)>'
	83: from /home/roman/.rvm/gems/ruby-2.5.1/gems/spring-2.1.0/lib/spring/client.rb:30:in `run'
	82: from /home/roman/.rvm/gems/ruby-2.5.1/gems/spring-2.1.0/lib/spring/client/command.rb:7:in `call'
	81: from /home/roman/.rvm/gems/ruby-2.5.1/gems/spring-2.1.0/lib/spring/client/rails.rb:28:in `call'
	80: from /home/roman/.rvm/gems/ruby-2.5.1/gems/spring-2.1.0/lib/spring/client/rails.rb:28:in `load'
	79: from /home/roman/code/Kawaii/bin/rails:9:in `<top (required)>'
	78: from /home/roman/.rvm/gems/ruby-2.5.1/gems/activesupport-6.0.2.1/lib/active_support/dependencies.rb:325:in `require'
	77: from /home/roman/.rvm/gems/ruby-2.5.1/gems/activesupport-6.0.2.1/lib/active_support/dependencies.rb:291:in `load_dependency'
	76: from /home/roman/.rvm/gems/ruby-2.5.1/gems/activesupport-6.0.2.1/lib/active_support/dependencies.rb:325:in `block in require'
	75: from /home/roman/.rvm/gems/ruby-2.5.1/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
	74: from /home/roman/.rvm/gems/ruby-2.5.1/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `require_with_bootsnap_lfi'
	73: from /home/roman/.rvm/gems/ruby-2.5.1/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register'
	72: from /home/roman/.rvm/gems/ruby-2.5.1/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `block in require_with_bootsnap_lfi'
	71: from /home/roman/.rvm/gems/ruby-2.5.1/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require'
	70: from /home/roman/.rvm/gems/ruby-2.5.1/gems/railties-6.0.2.1/lib/rails/commands.rb:18:in `<top (required)>'
	69: from /home/roman/.rvm/gems/ruby-2.5.1/gems/railties-6.0.2.1/lib/rails/command.rb:46:in `invoke'
	68: from /home/roman/.rvm/gems/ruby-2.5.1/gems/railties-6.0.2.1/lib/rails/command/base.rb:69:in `perform'
	67: from /home/roman/.rvm/gems/ruby-2.5.1/gems/thor-1.0.1/lib/thor.rb:392:in `dispatch'
	66: from /home/roman/.rvm/gems/ruby-2.5.1/gems/thor-1.0.1/lib/thor/invocation.rb:127:in `invoke_command'
	65: from /home/roman/.rvm/gems/ruby-2.5.1/gems/thor-1.0.1/lib/thor/command.rb:27:in `run'
	64: from /home/roman/.rvm/gems/ruby-2.5.1/gems/railties-6.0.2.1/lib/rails/commands/server/server_command.rb:138:in `perform'
	63: from /home/roman/.rvm/gems/ruby-2.5.1/gems/railties-6.0.2.1/lib/rails/commands/server/server_command.rb:138:in `tap'
	62: from /home/roman/.rvm/gems/ruby-2.5.1/gems/railties-6.0.2.1/lib/rails/commands/server/server_command.rb:147:in `block in perform'
	61: from /home/roman/.rvm/gems/ruby-2.5.1/gems/railties-6.0.2.1/lib/rails/commands/server/server_command.rb:37:in `start'
	60: from /home/roman/.rvm/gems/ruby-2.5.1/gems/railties-6.0.2.1/lib/rails/commands/server/server_command.rb:77:in `log_to_stdout'
	59: from /home/roman/.rvm/gems/ruby-2.5.1/gems/rack-2.0.8/lib/rack/server.rb:354:in `wrapped_app'
	58: from /home/roman/.rvm/gems/ruby-2.5.1/gems/rack-2.0.8/lib/rack/server.rb:219:in `app'
	57: from /home/roman/.rvm/gems/ruby-2.5.1/gems/rack-2.0.8/lib/rack/server.rb:319:in `build_app_and_options_from_config'
	56: from /home/roman/.rvm/gems/ruby-2.5.1/gems/rack-2.0.8/lib/rack/builder.rb:40:in `parse_file'
	55: from /home/roman/.rvm/gems/ruby-2.5.1/gems/rack-2.0.8/lib/rack/builder.rb:49:in `new_from_string'
	54: from /home/roman/.rvm/gems/ruby-2.5.1/gems/rack-2.0.8/lib/rack/builder.rb:49:in `eval'
	53: from config.ru:in `<main>'
	52: from config.ru:in `new'
	51: from /home/roman/.rvm/gems/ruby-2.5.1/gems/rack-2.0.8/lib/rack/builder.rb:55:in `initialize'
	50: from /home/roman/.rvm/gems/ruby-2.5.1/gems/rack-2.0.8/lib/rack/builder.rb:55:in `instance_eval'
	49: from config.ru:3:in `block in <main>'
	48: from /home/roman/.rvm/gems/ruby-2.5.1/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:48:in `require_relative'
	47: from /home/roman/.rvm/gems/ruby-2.5.1/gems/activesupport-6.0.2.1/lib/active_support/dependencies.rb:325:in `require'
	46: from /home/roman/.rvm/gems/ruby-2.5.1/gems/activesupport-6.0.2.1/lib/active_support/dependencies.rb:291:in `load_dependency'
	45: from /home/roman/.rvm/gems/ruby-2.5.1/gems/activesupport-6.0.2.1/lib/active_support/dependencies.rb:325:in `block in require'
	44: from /home/roman/.rvm/gems/ruby-2.5.1/gems/zeitwerk-2.2.2/lib/zeitwerk/kernel.rb:23:in `require'
	43: from /home/roman/.rvm/gems/ruby-2.5.1/gems/polyglot-0.3.5/lib/polyglot.rb:65:in `require'
	42: from /home/roman/.rvm/gems/ruby-2.5.1/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
	41: from /home/roman/.rvm/gems/ruby-2.5.1/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `require_with_bootsnap_lfi'
	40: from /home/roman/.rvm/gems/ruby-2.5.1/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register'
	39: from /home/roman/.rvm/gems/ruby-2.5.1/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `block in require_with_bootsnap_lfi'
	38: from /home/roman/.rvm/gems/ruby-2.5.1/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require'
	37: from /home/roman/code/Kawaii/config/environment.rb:5:in `<top (required)>'
	36: from /home/roman/.rvm/gems/ruby-2.5.1/gems/railties-6.0.2.1/lib/rails/application.rb:363:in `initialize!'
	35: from /home/roman/.rvm/gems/ruby-2.5.1/gems/railties-6.0.2.1/lib/rails/initializable.rb:60:in `run_initializers'
	34: from /home/roman/.rvm/rubies/ruby-2.5.1/lib/ruby/2.5.0/tsort.rb:205:in `tsort_each'
	33: from /home/roman/.rvm/rubies/ruby-2.5.1/lib/ruby/2.5.0/tsort.rb:226:in `tsort_each'
	32: from /home/roman/.rvm/rubies/ruby-2.5.1/lib/ruby/2.5.0/tsort.rb:347:in `each_strongly_connected_component'
	31: from /home/roman/.rvm/rubies/ruby-2.5.1/lib/ruby/2.5.0/tsort.rb:347:in `call'
	30: from /home/roman/.rvm/rubies/ruby-2.5.1/lib/ruby/2.5.0/tsort.rb:347:in `each'
	29: from /home/roman/.rvm/rubies/ruby-2.5.1/lib/ruby/2.5.0/tsort.rb:349:in `block in each_strongly_connected_component'
	28: from /home/roman/.rvm/rubies/ruby-2.5.1/lib/ruby/2.5.0/tsort.rb:431:in `each_strongly_connected_component_from'
	27: from /home/roman/.rvm/rubies/ruby-2.5.1/lib/ruby/2.5.0/tsort.rb:350:in `block (2 levels) in each_strongly_connected_component'
	26: from /home/roman/.rvm/rubies/ruby-2.5.1/lib/ruby/2.5.0/tsort.rb:228:in `block in tsort_each'
	25: from /home/roman/.rvm/gems/ruby-2.5.1/gems/railties-6.0.2.1/lib/rails/initializable.rb:61:in `block in run_initializers'
	24: from /home/roman/.rvm/gems/ruby-2.5.1/gems/railties-6.0.2.1/lib/rails/initializable.rb:32:in `run'
	23: from /home/roman/.rvm/gems/ruby-2.5.1/gems/railties-6.0.2.1/lib/rails/initializable.rb:32:in `instance_exec'
	22: from /home/roman/.rvm/gems/ruby-2.5.1/gems/railties-6.0.2.1/lib/rails/application/finisher.rb:113:in `block in <module:Finisher>'
	21: from /home/roman/.rvm/gems/ruby-2.5.1/gems/activesupport-6.0.2.1/lib/active_support/reloader.rb:88:in `prepare!'
	20: from /home/roman/.rvm/gems/ruby-2.5.1/gems/activesupport-6.0.2.1/lib/active_support/callbacks.rb:134:in `run_callbacks'
	19: from /home/roman/.rvm/gems/ruby-2.5.1/gems/activesupport-6.0.2.1/lib/active_support/callbacks.rb:514:in `invoke_before'
	18: from /home/roman/.rvm/gems/ruby-2.5.1/gems/activesupport-6.0.2.1/lib/active_support/callbacks.rb:514:in `each'
	17: from /home/roman/.rvm/gems/ruby-2.5.1/gems/activesupport-6.0.2.1/lib/active_support/callbacks.rb:514:in `block in invoke_before'
	16: from /home/roman/.rvm/gems/ruby-2.5.1/gems/activesupport-6.0.2.1/lib/active_support/callbacks.rb:202:in `block in halting'
	15: from /home/roman/.rvm/gems/ruby-2.5.1/gems/activesupport-6.0.2.1/lib/active_support/callbacks.rb:606:in `block in default_terminator'
	14: from /home/roman/.rvm/gems/ruby-2.5.1/gems/activesupport-6.0.2.1/lib/active_support/callbacks.rb:606:in `catch'
	13: from /home/roman/.rvm/gems/ruby-2.5.1/gems/activesupport-6.0.2.1/lib/active_support/callbacks.rb:607:in `block (2 levels) in default_terminator'
	12: from /home/roman/.rvm/gems/ruby-2.5.1/gems/activesupport-6.0.2.1/lib/active_support/callbacks.rb:201:in `block (2 levels) in halting'
	11: from /home/roman/.rvm/gems/ruby-2.5.1/gems/activesupport-6.0.2.1/lib/active_support/callbacks.rb:429:in `block in make_lambda'
	10: from /home/roman/.rvm/gems/ruby-2.5.1/gems/activesupport-6.0.2.1/lib/active_support/callbacks.rb:429:in `instance_exec'
	 9: from /home/roman/.rvm/gems/ruby-2.5.1/bundler/gems/solidus_sale_prices-bdb635fb2332/lib/solidus_sale_prices/engine.rb:13:in `activate'
	 8: from /home/roman/.rvm/gems/ruby-2.5.1/bundler/gems/solidus_sale_prices-bdb635fb2332/lib/solidus_sale_prices/engine.rb:13:in `glob'
	 7: from /home/roman/.rvm/gems/ruby-2.5.1/bundler/gems/solidus_sale_prices-bdb635fb2332/lib/solidus_sale_prices/engine.rb:14:in `block in activate'
	 6: from /home/roman/.rvm/gems/ruby-2.5.1/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:54:in `load'
	 5: from /home/roman/.rvm/gems/ruby-2.5.1/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:54:in `load'
	 4: from /home/roman/.rvm/gems/ruby-2.5.1/bundler/gems/solidus_sale_prices-bdb635fb2332/app/helpers/spree/base_helper_decorator.rb:1:in `<top (required)>'
	 3: from /home/roman/.rvm/gems/ruby-2.5.1/gems/zeitwerk-2.2.2/lib/zeitwerk/kernel.rb:16:in `require'
	 2: from /home/roman/.rvm/gems/ruby-2.5.1/gems/zeitwerk-2.2.2/lib/zeitwerk/kernel.rb:16:in `tap'
	 1: from /home/roman/.rvm/gems/ruby-2.5.1/gems/zeitwerk-2.2.2/lib/zeitwerk/kernel.rb:17:in `block in require'
/home/roman/.rvm/gems/ruby-2.5.1/gems/zeitwerk-2.2.2/lib/zeitwerk/loader/callbacks.rb:17:in `on_file_autoloaded': expected file /home/roman/.rvm/gems/ruby-2.5.1/bundler/gems/solidus_seo-970b16d37a66/app/helpers/spree/base_helper_decorator.rb to define constant Spree::BaseHelperDecorator, but didn't (Zeitwerk::NameError)
```

**Comment by b1nary** [comment]
It works perfectly when i load the gem before any other solidus gems

**Comment by b1nary** [comment]
I've tried to deploy this app and nope, sort order does not appear to fix anything on production.

Any ideas?

**Comment by dportalesr** [comment]
Hello, @b1nary! Can you please share with us which Rails and Solidus version are you using?

**Comment by dportalesr** [comment]
Can you also provide the contents of you `config/application.rb` and `Gemfile`, please?

**Comment by jontarg** [comment]
This should be fixed in latest version.
